### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by abelalmeida** [cs481-ekh/s23-volt#19]
As a developer I need to understand the Web API "Screen Capture API" so that I can create a the ability to play back web recording for the part of the project that needs to be able to play back the user's actions
**Acceptance Criteria:**
- [ ] #7
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
