### ISSUE TITLE
Bug Resolution

### ISSUE THREAD

**Issue by stocktonwoodworth** [cs481-ekh/s23-volt#47]
As a user, I want to avoid bugs so my experience isn't hindered.

**Acceptance Criteria:**
- [ ] #9 
- [x] #45
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
